services:
  db:
    image: pgvector/pgvector:pg16
    container_name: kindred-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: "5432:5432" # â†’ Implication: Remove this in production to prevent external DB access
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/database.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: kindred-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 5000

  frontend:
    build: ./frontend
    container_name: kindred-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=/api

volumes:
  pgdata:
