style: github
template: CHANGELOG.tpl.md

info:
  title: CHANGELOG
  repository_url: https://github.com/lucas-queiroz-sena2005/Kindred

options:
  commits:
    filters: {}  # sem filtro, aceita todos os commits

  commit_groups:
    title_maps:
      "Commits": "Commits"  # agrupa tudo na seção "Commits"

header:
  # captura qualquer mensagem inteira do commit
  pattern: "^(.*)$"
  pattern_maps:
    - Subject

notes:
  keywords:
    - BREAKING CHANGE
