style: github
template: CHANGELOG.tpl.md

info:
  title: CHANGELOG
  repository_url: https://github.com/lucas-queiroz-sena2005/Kindred

options:
  commits:
    filters: {}

  commit_groups:
    title_maps:
      feat: "âœ¨ Novas Funcionalidades"
      fix: "ğŸ› CorreÃ§Ãµes"
      perf: "âš¡ Melhorias de Performance"
      docs: "ğŸ“– DocumentaÃ§Ã£o"
      chore: "ğŸ§¹ ManutenÃ§Ã£o"
      refactor: "â™»ï¸ RefatoraÃ§Ã£o"
      test: "ğŸ§ª Testes"
      ci: "âš™ï¸ CI/CD"
      build: "ğŸ“¦ Build"
      style: "ğŸ¨ Estilo"
      security: "ğŸ” SeguranÃ§a"
      revert: "ğŸ”™ ReversÃµes"
      other: "ğŸ“¦ Outros"

header:
  pattern: '^(\w*)(?:\(([\w\ $\.\-\*]*)\))?: (.*)$'
  pattern_maps:
    - Type
    - Scope
    - Subject

notes:
  keywords:
    - BREAKING CHANGE
    - breaking change
    - security
